name: Pipeline CI/CD (Desarrollo)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    name: Integración Continua
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Instalar dependencias
      run: npm ci
      
    - name: Verificación de tipos
      run: npm run type-check
      
    - name: Ejecutar pruebas con cobertura
      run: npm run test:coverage
      
    - name: Construir aplicación
      run: npm run build
      
    - name: Subir artefactos de construcción
      uses: actions/upload-artifact@v4
      with:
        name: archivos-construccion
        path: dist/
        retention-days: 7
        
    - name: Subir reporte de cobertura
      uses: actions/upload-artifact@v4
      with:
        name: reporte-cobertura
        path: coverage/
        retention-days: 30

  # Nota: El despliegue a producción se maneja en docker-deploy.yml
  # cuando se hace push a la rama main 
